// <copyright file="ErrorMessage.cs" company="TheBIADevCompany">
// Copyright (c) TheBIADevCompany. All rights reserved.
// </copyright>

namespace TheBIADevCompany.BIATemplate.Crosscutting.Common.Error
{
    using System.Collections.Immutable;
    using BIA.Net.Core.Common.Error;
    using static TheBIADevCompany.BIATemplate.Crosscutting.Common.Constants;

    /// <summary>
    /// The class containing the error messages.
    /// </summary>
    public static class ErrorMessage
    {
        /// <summary>
        /// List of all custom error translated generated by the back.
        /// </summary>
        private static readonly ImmutableList<BiaErrorTranslation> Translations =
        [

            // Begin project error messages

            // End project error messages
        ];

        /// <summary>
        /// Fill the error translations.
        /// </summary>
        public static void FillErrorTranslations()
        {
            BiaErrorMessage.InitBiaErrorTranslations(LanguageId.English, LanguageId.French, LanguageId.Spanish);
            BiaErrorMessage.MergeTranslations(Translations);
        }
    }
}
